---
ID: "c3770a49-1bf0-4707-9e52-4eebd547b308"
Parent: "ef87e73b-c7ff-49a2-ac59-9b0be83755c3"
Template: "ef87e73b-c7ff-49a2-ac59-9b0be83755c3"
Path: /sitecore/templates/Feature/JSS Experience Accelerator/Page Content/Rendering Parameters/Page Content/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "af62d192-0bf7-41e7-b6e6-3fde602de309"
