---
ID: "96d9ad72-2b8c-4289-8733-7a575cbabc68"
Parent: "e71ab118-e008-4f6a-8000-1cc8eeee6266"
Template: "e71ab118-e008-4f6a-8000-1cc8eeee6266"
Path: /sitecore/templates/Project/BlogModule/Components/Header/HeaderFolder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{B990C9D8-ECFB-4341-831E-DFFCFA5E5A43}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250710T041918Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "07abe90a-5241-4459-b568-dc9903d9d7e2"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250710T041927Z
