---
ID: "c42cd5f1-74d2-42a0-bb4d-a39bf76b5ad7"
Parent: "3c8ab938-64b8-419d-b23d-d6fd75ce6ed4"
Template: "0437fee2-44c9-46a6-abe9-28858d9fee8c"
Path: /sitecore/templates/Foundation/JSS Experience Accelerator/Scaffolding/Base
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230130T144754Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "376f754a-3578-42bf-b634-6aa10cc64bf0"
