---
ID: "7f3c54fa-8fe5-4ada-80f9-4cbb38f20803"
Parent: "137fecf3-d3ed-4212-b57c-82faf828cc91"
Template: "137fecf3-d3ed-4212-b57c-82faf828cc91"
Path: /sitecore/templates/Project/BlogModule/Headless Tenant/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250704T093241Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8879c14b-7dad-4ed9-8b5c-9eeb5ac4b0a9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250704T093241Z
