/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore
import {
    Field,
    ImageField,
    FileField,
    LinkField,
    Item,
} from '@sitecore-jss/sitecore-jss-nextjs'
// @ts-ignore
import { Authors as SampleFeatureAuthors } from './Sample.Feature.model'
// @ts-ignore
import { BlogCompponent as SampleFeatureBlogCompponent } from './Sample.Feature.model'
// @ts-ignore
import { Cards as SampleFoundationCards } from './Sample.Foundation.model'
// @ts-ignore
import { BlogList as SampleFeatureBlogList } from './Sample.Feature.model'
// @ts-ignore
import { HeroBanner as SampleFeatureHeroBanner } from './Sample.Feature.model'
// @ts-ignore
import { Navigation as SampleFeatureNavigation } from './Sample.Feature.model'
// @ts-ignore
import { SocialLinks as SampleFeatureSocialLinks } from './Sample.Feature.model'

export namespace Authors {
    /**
     * Represents the template /sitecore/templates/Feature/BlogModule/Authors/Author Folder
     */
    export type AuthorFolder = {
        fields?: {}
    }

    /**
     * Represents the GraphQL template /sitecore/templates/Feature/BlogModule/Authors/Author Folder
     */
    export type AuthorFolderJson = {}

    /**
     * Represents the template /sitecore/templates/Feature/BlogModule/Authors/Authors
     */
    export type Authors = {
        fields?: {
            /**
             * Represents the age field (d3d39fa3-7510-47ce-9fb9-0fa895fde249).
             */
            age?: Field<number>

            /**
             * Represents the fullName field (dd254de7-3249-4b1c-8b43-3ada1bd35152).
             */
            fullName?: Field<string>
        }
    }

    /**
     * Represents the GraphQL template /sitecore/templates/Feature/BlogModule/Authors/Authors
     */
    export type AuthorsJson = {
        /**
         * Represents the age field (d3d39fa3-7510-47ce-9fb9-0fa895fde249).
         */
        age?: {
            jsonValue: Field<number>
        }

        /**
         * Represents the fullName field (dd254de7-3249-4b1c-8b43-3ada1bd35152).
         */
        fullName?: {
            jsonValue: Field<string>
        }
    }
}
export namespace BlogCompponent {
    /**
     * Represents the template /sitecore/templates/Feature/BlogModule/BlogCompponent/Blog
     */
    export type Blog = SampleFoundationCards.BaseCard & {
        fields: {
            /**
             * Represents the Author field (5908ba45-737e-4845-a6f0-79fb101f56f0).
             */
            author?: Item

            /**
             * Represents the Banner Image field (dbe3ded6-7ba2-40b9-b884-41da32f4a8f8).
             */
            bannerImage?: ImageField

            /**
             * Represents the Card Image field (2d3f5f5b-92ce-4b1d-8831-01158c4f35c0).
             */
            cardImage?: ImageField

            /**
             * Represents the description field (4d2ea5c8-bb20-4d31-90a8-a99847643aa5).
             */
            description?: Field<string>

            /**
             * Represents the Go to Blog CTALink field (686f9e5b-1171-43ad-a2e4-58c530d00d16).
             */
            goToBlog?: Field<string>

            /**
             * Represents the Is Archived  field (dcb01b73-5a09-482c-971a-fb2c392bc12b).
             */
            isArchived?: Field<boolean>

            /**
             * Represents the Is Featured field (3f6dd9a3-d1f3-4763-b28a-441fb8a826ee).
             */
            isFeatured?: Field<boolean>

            /**
             * Represents the Related Blog field (511e2b64-dccc-4d46-affa-6624c0d78610).
             */
            relatedBlog?: Item[]
        }
    }

    /**
     * Represents the GraphQL template /sitecore/templates/Feature/BlogModule/BlogCompponent/Blog
     */
    export type BlogJson = SampleFoundationCards.BaseCardJson & {
        /**
         * Represents the Author field (5908ba45-737e-4845-a6f0-79fb101f56f0).
         */
        author?: {
            jsonValue: Item
        }

        /**
         * Represents the Banner Image field (dbe3ded6-7ba2-40b9-b884-41da32f4a8f8).
         */
        bannerImage?: {
            jsonValue: ImageField
        }

        /**
         * Represents the Card Image field (2d3f5f5b-92ce-4b1d-8831-01158c4f35c0).
         */
        cardImage?: {
            jsonValue: ImageField
        }

        /**
         * Represents the description field (4d2ea5c8-bb20-4d31-90a8-a99847643aa5).
         */
        description?: {
            jsonValue: Field<string>
        }

        /**
         * Represents the Go to Blog CTALink field (686f9e5b-1171-43ad-a2e4-58c530d00d16).
         */
        goToBlog?: {
            jsonValue: Field<string>
        }

        /**
         * Represents the Is Archived  field (dcb01b73-5a09-482c-971a-fb2c392bc12b).
         */
        isArchived?: {
            jsonValue: Field<boolean>
        }

        /**
         * Represents the Is Featured field (3f6dd9a3-d1f3-4763-b28a-441fb8a826ee).
         */
        isFeatured?: {
            jsonValue: Field<boolean>
        }

        /**
         * Represents the Related Blog field (511e2b64-dccc-4d46-affa-6624c0d78610).
         */
        relatedBlog?: {
            jsonValue: Item[]
        }
    }

    /**
     * Represents the template /sitecore/templates/Feature/BlogModule/BlogCompponent/Blog Folder
     */
    export type BlogFolder = {
        fields?: {}
    }

    /**
     * Represents the GraphQL template /sitecore/templates/Feature/BlogModule/BlogCompponent/Blog Folder
     */
    export type BlogFolderJson = {}
}
export namespace BlogList {
    /**
     * Represents the template /sitecore/templates/Feature/BlogModule/BlogList/Blog List Folder
     */
    export type BlogListFolder = {
        fields?: {}
    }

    /**
     * Represents the GraphQL template /sitecore/templates/Feature/BlogModule/BlogList/Blog List Folder
     */
    export type BlogListFolderJson = {}

    /**
     * Represents the template /sitecore/templates/Feature/BlogModule/BlogList/BlogList
     */
    export type BlogList = {
        fields?: {
            /**
             * Represents the Blogs field (71f4de75-f38a-4e96-b177-0d6488eb3339).
             */
            blogs?: Item[]

            /**
             * Represents the Title field (bfc2e74d-4553-45d7-8d2e-7ac45ef89a28).
             */
            title?: Field<string>
        }
    }

    /**
     * Represents the GraphQL template /sitecore/templates/Feature/BlogModule/BlogList/BlogList
     */
    export type BlogListJson = {
        /**
         * Represents the Blogs field (71f4de75-f38a-4e96-b177-0d6488eb3339).
         */
        blogs?: {
            jsonValue: Item[]
        }

        /**
         * Represents the Title field (bfc2e74d-4553-45d7-8d2e-7ac45ef89a28).
         */
        title?: {
            jsonValue: Field<string>
        }
    }
}
export namespace HeroBanner {
    /**
     * Represents the template /sitecore/templates/Feature/BlogModule/HeroBanner/HeroBanner
     */
    export type HeroBanner = {
        fields?: {
            /**
             * Represents the description field (35c77726-1713-4a1a-bb3e-04ef3f92fba6).
             */
            description?: Field<string>

            /**
             * Represents the image field (2c5baff0-0470-45a3-bd02-136e9e887211).
             */
            image?: ImageField

            /**
             * Represents the title field (d0a7f7e4-faac-44d1-91b6-f53542d73871).
             */
            title?: Field<string>
        }
    }

    /**
     * Represents the GraphQL template /sitecore/templates/Feature/BlogModule/HeroBanner/HeroBanner
     */
    export type HeroBannerJson = {
        /**
         * Represents the description field (35c77726-1713-4a1a-bb3e-04ef3f92fba6).
         */
        description?: {
            jsonValue: Field<string>
        }

        /**
         * Represents the image field (2c5baff0-0470-45a3-bd02-136e9e887211).
         */
        image?: {
            jsonValue: ImageField
        }

        /**
         * Represents the title field (d0a7f7e4-faac-44d1-91b6-f53542d73871).
         */
        title?: {
            jsonValue: Field<string>
        }
    }

    /**
     * Represents the template /sitecore/templates/Feature/BlogModule/HeroBanner/HeroBannerFolder
     */
    export type HeroBannerFolder = {
        fields?: {}
    }

    /**
     * Represents the GraphQL template /sitecore/templates/Feature/BlogModule/HeroBanner/HeroBannerFolder
     */
    export type HeroBannerFolderJson = {}
}
export namespace Navigation {
    /**
     * Represents the template /sitecore/templates/Feature/BlogModule/Navigation/NavLink
     */
    export type NavLink = {
        fields?: {
            /**
             * Represents the link field (66df7b09-78ad-4369-ab41-a6f145f84339).
             */
            link?: LinkField

            /**
             * Represents the title field (1dd71d4c-be0b-4a2d-abf3-74931b489db0).
             */
            title?: Field<string>
        }
    }

    /**
     * Represents the GraphQL template /sitecore/templates/Feature/BlogModule/Navigation/NavLink
     */
    export type NavLinkJson = {
        /**
         * Represents the link field (66df7b09-78ad-4369-ab41-a6f145f84339).
         */
        link?: {
            jsonValue: LinkField
        }

        /**
         * Represents the title field (1dd71d4c-be0b-4a2d-abf3-74931b489db0).
         */
        title?: {
            jsonValue: Field<string>
        }
    }

    /**
     * Represents the template /sitecore/templates/Feature/BlogModule/Navigation/NavMenu
     */
    export type NavMenu = {
        fields?: {
            /**
             * Represents the DrawerLogo field (c352a8c0-7e86-4111-a82a-4ed216896bc1).
             */
            DrawerLogo?: ImageField

            /**
             * Represents the menu field (8b477309-39cb-4958-bd50-104f42cbbb8c).
             */
            menu?: Item[]
        }
    }

    /**
     * Represents the GraphQL template /sitecore/templates/Feature/BlogModule/Navigation/NavMenu
     */
    export type NavMenuJson = {
        /**
         * Represents the DrawerLogo field (c352a8c0-7e86-4111-a82a-4ed216896bc1).
         */
        DrawerLogo?: {
            jsonValue: ImageField
        }

        /**
         * Represents the menu field (8b477309-39cb-4958-bd50-104f42cbbb8c).
         */
        menu?: {
            jsonValue: Item[]
        }
    }

    /**
     * Represents the template /sitecore/templates/Feature/BlogModule/Navigation/Navigation Link Folder
     */
    export type NavigationLinkFolder = {
        fields?: {}
    }

    /**
     * Represents the GraphQL template /sitecore/templates/Feature/BlogModule/Navigation/Navigation Link Folder
     */
    export type NavigationLinkFolderJson = {}

    /**
     * Represents the template /sitecore/templates/Feature/BlogModule/Navigation/Navigation List Folder
     */
    export type NavigationListFolder = {
        fields?: {}
    }

    /**
     * Represents the GraphQL template /sitecore/templates/Feature/BlogModule/Navigation/Navigation List Folder
     */
    export type NavigationListFolderJson = {}
}
export namespace SocialLinks {
    /**
     * Represents the template /sitecore/templates/Feature/BlogModule/SocialLinks/Social Link Folder
     */
    export type SocialLinkFolder = {
        fields?: {}
    }

    /**
     * Represents the GraphQL template /sitecore/templates/Feature/BlogModule/SocialLinks/Social Link Folder
     */
    export type SocialLinkFolderJson = {}

    /**
     * Represents the template /sitecore/templates/Feature/BlogModule/SocialLinks/SocialLink
     */
    export type SocialLink = {
        fields?: {
            /**
             * Represents the Logo field (b79502ef-93ef-4014-8ea3-5492472fcf02).
             */
            logo?: ImageField

            /**
             * Represents the Navigation LInk field (639daf80-dfc9-4989-b9e7-8c05e9c3b723).
             */
            socialLink?: LinkField
        }
    }

    /**
     * Represents the GraphQL template /sitecore/templates/Feature/BlogModule/SocialLinks/SocialLink
     */
    export type SocialLinkJson = {
        /**
         * Represents the Logo field (b79502ef-93ef-4014-8ea3-5492472fcf02).
         */
        logo?: {
            jsonValue: ImageField
        }

        /**
         * Represents the Navigation LInk field (639daf80-dfc9-4989-b9e7-8c05e9c3b723).
         */
        socialLink?: {
            jsonValue: LinkField
        }
    }
}
