
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-jss/sitecore-jss-nextjs';
// @ts-ignore 
import { PageStructure as SampleFeaturePageStructure } from "./Sample.Feature.model"
// @ts-ignore 
import { Presentation as SampleFoundationPresentation } from "./Sample.Foundation.model"
// @ts-ignore 
import { Media as SampleFeatureMedia } from "./Sample.Feature.model"
// @ts-ignore 
import { Navigation as SampleFeatureNavigation } from "./Sample.Feature.model"
// @ts-ignore 
import { PageContent as SampleFeaturePageContent } from "./Sample.Feature.model"

export namespace PageStructure.RenderingParameters {

    /**
    * Represents the template /sitecore/templates/Feature/JSS Experience Accelerator/Page Structure/Rendering Parameters/ColumnSplitter
    */
    export type ColumnSplitter = SampleFoundationPresentation.RenderingParameters.BaseRenderingParameters &  {
        fields?: { 
            /**
            * Represents the Column 1 layout field (292e92d0-5e59-48b4-8271-1ee910cfa0bc).
            */
            ColumnWidth1?: Field<string>;

            /**
            * Represents the Column 2 layout field (718ce476-be2d-4456-8b3d-cf0f2a312cdf).
            */
            ColumnWidth2?: Field<string>;

            /**
            * Represents the Column 3 layout field (bba175b5-49f3-41e7-953d-5615c842530f).
            */
            ColumnWidth3?: Field<string>;

            /**
            * Represents the Column 4 layout field (4496cf32-a24c-4210-8eff-b3fc62c967f1).
            */
            ColumnWidth4?: Field<string>;

            /**
            * Represents the Column 5 layout field (7cbf006e-6cfc-4e54-beeb-bb07542f289f).
            */
            ColumnWidth5?: Field<string>;

            /**
            * Represents the Column 6 layout field (33beaa03-6cbc-497a-a8f9-0979f06ed121).
            */
            ColumnWidth6?: Field<string>;

            /**
            * Represents the Column 7 layout field (3e3b0657-1079-4e0b-ae04-bd9e93eca36b).
            */
            ColumnWidth7?: Field<string>;

            /**
            * Represents the Column 8 layout field (bb9fc77c-03c2-4c51-a620-5c65513711f1).
            */
            ColumnWidth8?: Field<string>;

            /**
            * Represents the Styles for column 1 field (a2c4abb2-90e9-4866-a428-753bf286c7a5).
            */
            Styles1?: Field<string>;

            /**
            * Represents the Styles for column 2 field (79777c28-bcd3-4c20-8c2a-abc99c3a4a6a).
            */
            Styles2?: Field<string>;

            /**
            * Represents the Styles for column 3 field (591a783f-f3fd-4239-b233-1dad96d18be2).
            */
            Styles3?: Field<string>;

            /**
            * Represents the Styles for column 4 field (fdda06c2-8d15-46e7-a562-0f8de50aaedd).
            */
            Styles4?: Field<string>;

            /**
            * Represents the Styles for column 5 field (150e00cc-82c8-4ce5-8b46-86a2769d481d).
            */
            Styles5?: Field<string>;

            /**
            * Represents the Styles for column 6 field (9f5dcccf-418d-49a2-8df9-b43f4011b0d1).
            */
            Styles6?: Field<string>;

            /**
            * Represents the Styles for column 7 field (56eff754-65c8-4470-992a-1b1ed8a06014).
            */
            Styles7?: Field<string>;

            /**
            * Represents the Styles for column 8 field (47941461-f5b5-4707-804b-69990971e6a1).
            */
            Styles8?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/JSS Experience Accelerator/Page Structure/Rendering Parameters/ColumnSplitter
    */
    export type ColumnSplitterJson = SampleFoundationPresentation.RenderingParameters.BaseRenderingParametersJson &  {
        
            /**
            * Represents the Column 1 layout field (292e92d0-5e59-48b4-8271-1ee910cfa0bc).
            */
            ColumnWidth1?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Column 2 layout field (718ce476-be2d-4456-8b3d-cf0f2a312cdf).
            */
            ColumnWidth2?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Column 3 layout field (bba175b5-49f3-41e7-953d-5615c842530f).
            */
            ColumnWidth3?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Column 4 layout field (4496cf32-a24c-4210-8eff-b3fc62c967f1).
            */
            ColumnWidth4?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Column 5 layout field (7cbf006e-6cfc-4e54-beeb-bb07542f289f).
            */
            ColumnWidth5?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Column 6 layout field (33beaa03-6cbc-497a-a8f9-0979f06ed121).
            */
            ColumnWidth6?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Column 7 layout field (3e3b0657-1079-4e0b-ae04-bd9e93eca36b).
            */
            ColumnWidth7?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Column 8 layout field (bb9fc77c-03c2-4c51-a620-5c65513711f1).
            */
            ColumnWidth8?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Styles for column 1 field (a2c4abb2-90e9-4866-a428-753bf286c7a5).
            */
            Styles1?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Styles for column 2 field (79777c28-bcd3-4c20-8c2a-abc99c3a4a6a).
            */
            Styles2?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Styles for column 3 field (591a783f-f3fd-4239-b233-1dad96d18be2).
            */
            Styles3?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Styles for column 4 field (fdda06c2-8d15-46e7-a562-0f8de50aaedd).
            */
            Styles4?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Styles for column 5 field (150e00cc-82c8-4ce5-8b46-86a2769d481d).
            */
            Styles5?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Styles for column 6 field (9f5dcccf-418d-49a2-8df9-b43f4011b0d1).
            */
            Styles6?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Styles for column 7 field (56eff754-65c8-4470-992a-1b1ed8a06014).
            */
            Styles7?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Styles for column 8 field (47941461-f5b5-4707-804b-69990971e6a1).
            */
            Styles8?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/JSS Experience Accelerator/Page Structure/Rendering Parameters/Container
    */
    export type Container = SampleFoundationPresentation.RenderingParameters.BaseRenderingParameters &  {
        fields?: { 
            /**
            * Represents the Background image field (6845679d-e298-4e94-96eb-230cb7c3baae).
            */
            BackgroundImage?: ImageField;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/JSS Experience Accelerator/Page Structure/Rendering Parameters/Container
    */
    export type ContainerJson = SampleFoundationPresentation.RenderingParameters.BaseRenderingParametersJson &  {
        
            /**
            * Represents the Background image field (6845679d-e298-4e94-96eb-230cb7c3baae).
            */
            BackgroundImage?: {
                jsonValue: ImageField
            };


    }
}
export namespace Media {

    /**
    * Represents the template /sitecore/templates/Feature/JSS Experience Accelerator/Media/Image
    */
    export type Image =  {
        fields?: { 
            /**
            * Represents the Image field (57caf172-ce57-4e48-b3a1-46f8aea71c08).
            */
            Image?: ImageField;

            /**
            * Represents the Caption field (4d7b05d0-0300-486f-8f87-57de34a9b793).
            */
            ImageCaption?: Field<string>;

            /**
            * Represents the URL field (75fbf1b1-e7c5-494b-9633-693909f79425).
            */
            TargetUrl?: LinkField;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/JSS Experience Accelerator/Media/Image
    */
    export type ImageJson =  {
        
            /**
            * Represents the Image field (57caf172-ce57-4e48-b3a1-46f8aea71c08).
            */
            Image?: {
                jsonValue: ImageField
            };

            /**
            * Represents the Caption field (4d7b05d0-0300-486f-8f87-57de34a9b793).
            */
            ImageCaption?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the URL field (75fbf1b1-e7c5-494b-9633-693909f79425).
            */
            TargetUrl?: {
                jsonValue: LinkField
            };


    }
}
export namespace Media.RenderingParameters {

    /**
    * Represents the template /sitecore/templates/Feature/JSS Experience Accelerator/Media/Rendering Parameters/Image
    */
    export type Image = SampleFoundationPresentation.RenderingParameters.BaseRenderingParameters &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/JSS Experience Accelerator/Media/Rendering Parameters/Image
    */
    export type ImageJson = SampleFoundationPresentation.RenderingParameters.BaseRenderingParametersJson &  {
        

    }
}
export namespace Media {

    /**
    * Represents the template /sitecore/templates/Feature/JSS Experience Accelerator/Media/Image Folder
    */
    export type ImageFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/JSS Experience Accelerator/Media/Image Folder
    */
    export type ImageFolderJson =  {
        

    }
}
export namespace Navigation.Datasource {

    /**
    * Represents the template /sitecore/templates/Feature/JSS Experience Accelerator/Navigation/Datasource/Link
    */
    export type Link =  {
        fields?: { 
            /**
            * Represents the Link field (68c2a603-f98e-42a3-be2d-dd70598c2a63).
            */
            Link?: LinkField;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/JSS Experience Accelerator/Navigation/Datasource/Link
    */
    export type LinkJson =  {
        
            /**
            * Represents the Link field (68c2a603-f98e-42a3-be2d-dd70598c2a63).
            */
            Link?: {
                jsonValue: LinkField
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/JSS Experience Accelerator/Navigation/Datasource/Link List
    */
    export type LinkList =  {
        fields?: { 
            /**
            * Represents the Title field (dc9aaee9-fc44-458d-a9fb-bac61d8b0234).
            */
            Title?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/JSS Experience Accelerator/Navigation/Datasource/Link List
    */
    export type LinkListJson =  {
        
            /**
            * Represents the Title field (dc9aaee9-fc44-458d-a9fb-bac61d8b0234).
            */
            Title?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/JSS Experience Accelerator/Navigation/Datasource/Link List Folder
    */
    export type LinkListFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/JSS Experience Accelerator/Navigation/Datasource/Link List Folder
    */
    export type LinkListFolderJson =  {
        

    }
}
export namespace Navigation.RenderingParameters {

    /**
    * Represents the template /sitecore/templates/Feature/JSS Experience Accelerator/Navigation/Rendering Parameters/LinkList
    */
    export type LinkList = SampleFoundationPresentation.RenderingParameters.BaseRenderingParameters &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/JSS Experience Accelerator/Navigation/Rendering Parameters/LinkList
    */
    export type LinkListJson = SampleFoundationPresentation.RenderingParameters.BaseRenderingParametersJson &  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/JSS Experience Accelerator/Navigation/Rendering Parameters/Navigation
    */
    export type Navigation = SampleFoundationPresentation.RenderingParameters.BaseRenderingParameters &  {
        fields?: { 
            /**
            * Represents the Serializer field names field (0b2c3107-f59d-46f1-b464-1657886c1c87).
            */
            SerializerFieldNames?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/JSS Experience Accelerator/Navigation/Rendering Parameters/Navigation
    */
    export type NavigationJson = SampleFoundationPresentation.RenderingParameters.BaseRenderingParametersJson &  {
        
            /**
            * Represents the Serializer field names field (0b2c3107-f59d-46f1-b464-1657886c1c87).
            */
            SerializerFieldNames?: {
                jsonValue: Field<string>
            };


    }
}
export namespace PageContent.RenderingParameters {

    /**
    * Represents the template /sitecore/templates/Feature/JSS Experience Accelerator/Page Content/Rendering Parameters/Page Content
    */
    export type PageContent = SampleFoundationPresentation.RenderingParameters.BaseRenderingParameters &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/JSS Experience Accelerator/Page Content/Rendering Parameters/Page Content
    */
    export type PageContentJson = SampleFoundationPresentation.RenderingParameters.BaseRenderingParametersJson &  {
        

    }
}
export namespace PageContent {

    /**
    * Represents the template /sitecore/templates/Feature/JSS Experience Accelerator/Page Content/Promo
    */
    export type Promo =  {
        fields?: { 
            /**
            * Represents the Image field (f94b9858-c439-4291-863b-757b536c8b65).
            */
            PromoIcon?: ImageField;

            /**
            * Represents the Image 2 field (739c6cc2-0031-463d-9599-13478fd50ee3).
            */
            PromoIcon2?: ImageField;

            /**
            * Represents the Link field (ef24bed2-46ab-4d53-ad1a-1019935a4e89).
            */
            PromoLink?: LinkField;

            /**
            * Represents the Text field (28079f3a-896b-4273-be5f-59d0ebb7cd7d).
            */
            PromoText?: Field<string>;

            /**
            * Represents the Text 2 field (1f66862d-a5e3-405f-8e3e-b787b4c39b12).
            */
            PromoText2?: Field<string>;

            /**
            * Represents the Text 3 field (c6e604c3-5371-4e67-83df-a09a5ea66249).
            */
            PromoText3?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/JSS Experience Accelerator/Page Content/Promo
    */
    export type PromoJson =  {
        
            /**
            * Represents the Image field (f94b9858-c439-4291-863b-757b536c8b65).
            */
            PromoIcon?: {
                jsonValue: ImageField
            };

            /**
            * Represents the Image 2 field (739c6cc2-0031-463d-9599-13478fd50ee3).
            */
            PromoIcon2?: {
                jsonValue: ImageField
            };

            /**
            * Represents the Link field (ef24bed2-46ab-4d53-ad1a-1019935a4e89).
            */
            PromoLink?: {
                jsonValue: LinkField
            };

            /**
            * Represents the Text field (28079f3a-896b-4273-be5f-59d0ebb7cd7d).
            */
            PromoText?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Text 2 field (1f66862d-a5e3-405f-8e3e-b787b4c39b12).
            */
            PromoText2?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Text 3 field (c6e604c3-5371-4e67-83df-a09a5ea66249).
            */
            PromoText3?: {
                jsonValue: Field<string>
            };


    }
}
export namespace PageContent.RenderingParameters {

    /**
    * Represents the template /sitecore/templates/Feature/JSS Experience Accelerator/Page Content/Rendering Parameters/Promo
    */
    export type Promo = SampleFoundationPresentation.RenderingParameters.BaseRenderingParameters &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/JSS Experience Accelerator/Page Content/Rendering Parameters/Promo
    */
    export type PromoJson = SampleFoundationPresentation.RenderingParameters.BaseRenderingParametersJson &  {
        

    }
}
export namespace PageContent {

    /**
    * Represents the template /sitecore/templates/Feature/JSS Experience Accelerator/Page Content/Promo Folder
    */
    export type PromoFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/JSS Experience Accelerator/Page Content/Promo Folder
    */
    export type PromoFolderJson =  {
        

    }
}
export namespace PageContent.RenderingParameters {

    /**
    * Represents the template /sitecore/templates/Feature/JSS Experience Accelerator/Page Content/Rendering Parameters/Rich Text
    */
    export type RichText = SampleFoundationPresentation.RenderingParameters.BaseRenderingParameters &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/JSS Experience Accelerator/Page Content/Rendering Parameters/Rich Text
    */
    export type RichTextJson = SampleFoundationPresentation.RenderingParameters.BaseRenderingParametersJson &  {
        

    }
}
export namespace PageStructure.RenderingParameters {

    /**
    * Represents the template /sitecore/templates/Feature/JSS Experience Accelerator/Page Structure/Rendering Parameters/RowSplitter
    */
    export type RowSplitter = SampleFoundationPresentation.RenderingParameters.BaseRenderingParameters &  {
        fields?: { 
            /**
            * Represents the Styles for row 1 field (22e04fba-7af3-4efe-91d0-91c96c50e8f6).
            */
            Styles1?: Field<string>;

            /**
            * Represents the Styles for row 2 field (2d4dff46-7563-4671-a6e7-cfdb6bc2a175).
            */
            Styles2?: Field<string>;

            /**
            * Represents the Styles for row 3 field (6b44b72d-2c7d-4089-b7b9-afa4e1ddd5f5).
            */
            Styles3?: Field<string>;

            /**
            * Represents the Styles for row 4 field (dd4a8f2a-3a6c-4f00-a164-620eda04459f).
            */
            Styles4?: Field<string>;

            /**
            * Represents the Styles for row 5 field (deb68026-9f4c-4c43-9c4f-e37299ab7d26).
            */
            Styles5?: Field<string>;

            /**
            * Represents the Styles for row 6 field (b0d40ee8-fa8e-4fd8-bd08-206294897c7c).
            */
            Styles6?: Field<string>;

            /**
            * Represents the Styles for row 7 field (41d71e94-ef5b-4883-a1e1-fc28ac995b73).
            */
            Styles7?: Field<string>;

            /**
            * Represents the Styles for row 8 field (9ba62b79-b72e-4d63-a123-5fed10f694d1).
            */
            Styles8?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/JSS Experience Accelerator/Page Structure/Rendering Parameters/RowSplitter
    */
    export type RowSplitterJson = SampleFoundationPresentation.RenderingParameters.BaseRenderingParametersJson &  {
        
            /**
            * Represents the Styles for row 1 field (22e04fba-7af3-4efe-91d0-91c96c50e8f6).
            */
            Styles1?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Styles for row 2 field (2d4dff46-7563-4671-a6e7-cfdb6bc2a175).
            */
            Styles2?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Styles for row 3 field (6b44b72d-2c7d-4089-b7b9-afa4e1ddd5f5).
            */
            Styles3?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Styles for row 4 field (dd4a8f2a-3a6c-4f00-a164-620eda04459f).
            */
            Styles4?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Styles for row 5 field (deb68026-9f4c-4c43-9c4f-e37299ab7d26).
            */
            Styles5?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Styles for row 6 field (b0d40ee8-fa8e-4fd8-bd08-206294897c7c).
            */
            Styles6?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Styles for row 7 field (41d71e94-ef5b-4883-a1e1-fc28ac995b73).
            */
            Styles7?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Styles for row 8 field (9ba62b79-b72e-4d63-a123-5fed10f694d1).
            */
            Styles8?: {
                jsonValue: Field<string>
            };


    }
}
export namespace PageContent {

    /**
    * Represents the template /sitecore/templates/Feature/JSS Experience Accelerator/Page Content/Text
    */
    export type Text =  {
        fields?: { 
            /**
            * Represents the Text field (729034fc-24f3-40b7-8fa4-fb49d7de20dd).
            */
            Text?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/JSS Experience Accelerator/Page Content/Text
    */
    export type TextJson =  {
        
            /**
            * Represents the Text field (729034fc-24f3-40b7-8fa4-fb49d7de20dd).
            */
            Text?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/JSS Experience Accelerator/Page Content/Text Folder
    */
    export type TextFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/JSS Experience Accelerator/Page Content/Text Folder
    */
    export type TextFolderJson =  {
        

    }
}
export namespace PageContent.RenderingParameters {

    /**
    * Represents the template /sitecore/templates/Feature/JSS Experience Accelerator/Page Content/Rendering Parameters/Title
    */
    export type Title = SampleFoundationPresentation.RenderingParameters.BaseRenderingParameters &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/JSS Experience Accelerator/Page Content/Rendering Parameters/Title
    */
    export type TitleJson = SampleFoundationPresentation.RenderingParameters.BaseRenderingParametersJson &  {
        

    }
}


