
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-jss/sitecore-jss-nextjs';
// @ts-ignore 
import { Cards as SampleFoundationCards } from "./Sample.Foundation.model"

export namespace Cards {

    /**
    * Represents the template /sitecore/templates/Foundation/Base Components/Cards/Base Card
    */
    export type BaseCard =  {
        fields?: { 
            /**
            * Represents the content field (cf17dfe1-3883-4130-8cc4-df7163c27a2c).
            */
            content?: Field<string>;

            /**
            * Represents the image field (4cdfe26a-4b8b-4476-88a7-94d7e71379b5).
            */
            image?: ImageField;

            /**
            * Represents the title field (5dbb37bc-547a-4623-8796-92eacc63b10e).
            */
            title?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/Base Components/Cards/Base Card
    */
    export type BaseCardJson =  {
        
            /**
            * Represents the content field (cf17dfe1-3883-4130-8cc4-df7163c27a2c).
            */
            content?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the image field (4cdfe26a-4b8b-4476-88a7-94d7e71379b5).
            */
            image?: {
                jsonValue: ImageField
            };

            /**
            * Represents the title field (5dbb37bc-547a-4623-8796-92eacc63b10e).
            */
            title?: {
                jsonValue: Field<string>
            };


    }
}


