
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-jss/sitecore-jss-nextjs';
// @ts-ignore 
import { RenderingParams as SampleProjectRenderingParams } from "./Sample.Project.model"
// @ts-ignore 
import { Sample as SampleProjectSample } from "./Sample.Project.model"
// @ts-ignore 
import { Components as SampleProjectComponents } from "./Sample.Project.model"
// @ts-ignore 
import { Multisite as SampleFoundationMultisite } from "./Sample.Foundation.model"
// @ts-ignore 
import { Presentation as SampleFoundationPresentation } from "./Sample.Foundation.model"

export namespace RenderingParams {

    /**
    * Represents the template /sitecore/templates/Project/BlogModule/Rendering Params/Color
    */
    export type Color =  {
        fields?: { 
            /**
            * Represents the color field (a904edf3-1b3c-4935-98fc-56c7301347ca).
            */
            color?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/BlogModule/Rendering Params/Color
    */
    export type ColorJson =  {
        
            /**
            * Represents the color field (a904edf3-1b3c-4935-98fc-56c7301347ca).
            */
            color?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Project/BlogModule/Rendering Params/ColorParams
    */
    export type ColorParams =  {
        fields?: { 
            /**
            * Represents the backgroundColor field (58e154ea-c655-415a-b149-cf2ae0bc10dd).
            */
            backgroundColor?: Field<string>;

            /**
            * Represents the textColor field (8d0c5b20-8e99-4fb3-a365-ffa72c2ae619).
            */
            textColor?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/BlogModule/Rendering Params/ColorParams
    */
    export type ColorParamsJson =  {
        
            /**
            * Represents the backgroundColor field (58e154ea-c655-415a-b149-cf2ae0bc10dd).
            */
            backgroundColor?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the textColor field (8d0c5b20-8e99-4fb3-a365-ffa72c2ae619).
            */
            textColor?: {
                jsonValue: Field<string>
            };


    }
}
export namespace Sample.Project.BlogModule {

    /**
    * Represents the template /sitecore/templates/Project/BlogModule/Folder
    */
    export type Folder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/BlogModule/Folder
    */
    export type FolderJson =  {
        

    }
}
export namespace Components.Header {

    /**
    * Represents the template /sitecore/templates/Project/BlogModule/Components/Header/Header
    */
    export type Header =  {
        fields?: { 
            /**
            * Represents the Logo field (abc2325b-9e41-48f9-af64-534f54c698f6).
            */
            Logo?: ImageField;

            /**
            * Represents the Navigation field (144ce21d-0eeb-4dc0-8a99-059cf37a1ea7).
            */
            Navigation?: Item;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/BlogModule/Components/Header/Header
    */
    export type HeaderJson =  {
        
            /**
            * Represents the Logo field (abc2325b-9e41-48f9-af64-534f54c698f6).
            */
            Logo?: {
                jsonValue: ImageField
            };

            /**
            * Represents the Navigation field (144ce21d-0eeb-4dc0-8a99-059cf37a1ea7).
            */
            Navigation?: {
                jsonValue: Item
            };


    }

    /**
    * Represents the template /sitecore/templates/Project/BlogModule/Components/Header/HeaderFolder
    */
    export type HeaderFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/BlogModule/Components/Header/HeaderFolder
    */
    export type HeaderFolderJson =  {
        

    }
}
export namespace Sample.Project.BlogModule {

    /**
    * Represents the template /sitecore/templates/Project/BlogModule/Headless Site
    */
    export type HeadlessSite = SampleFoundationMultisite.HeadlessSite &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/BlogModule/Headless Site
    */
    export type HeadlessSiteJson = SampleFoundationMultisite.HeadlessSiteJson &  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/BlogModule/Headless Tenant
    */
    export type HeadlessTenant = SampleFoundationMultisite.HeadlessTenant &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/BlogModule/Headless Tenant
    */
    export type HeadlessTenantJson = SampleFoundationMultisite.HeadlessTenantJson &  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/BlogModule/JSS Settings
    */
    export type JssSettings = SampleFoundationMultisite.JssSettings &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/BlogModule/JSS Settings
    */
    export type JssSettingsJson = SampleFoundationMultisite.JssSettingsJson &  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/BlogModule/Page
    */
    export type Page = SampleFoundationMultisite.BasePage &  {
        fields?: { 
            /**
            * Represents the Content field (eeb762f5-de26-4167-9d61-332e6f3ad736).
            */
            Content?: Field<string>;

            /**
            * Represents the Title field (3575001e-8722-4307-b42f-ec27194089aa).
            */
            Title?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/BlogModule/Page
    */
    export type PageJson = SampleFoundationMultisite.BasePageJson &  {
        
            /**
            * Represents the Content field (eeb762f5-de26-4167-9d61-332e6f3ad736).
            */
            Content?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Title field (3575001e-8722-4307-b42f-ec27194089aa).
            */
            Title?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Project/BlogModule/Page Design Folder
    */
    export type PageDesignFolder = SampleFoundationPresentation.Folders.PageDesignFolder &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/BlogModule/Page Design Folder
    */
    export type PageDesignFolderJson = SampleFoundationPresentation.Folders.PageDesignFolderJson &  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/BlogModule/Page Designs
    */
    export type PageDesigns = SampleFoundationPresentation.PageDesigns &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/BlogModule/Page Designs
    */
    export type PageDesignsJson = SampleFoundationPresentation.PageDesignsJson &  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/BlogModule/Partial Design Folder
    */
    export type PartialDesignFolder = SampleFoundationPresentation.Folders.PartialDesignFolder &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/BlogModule/Partial Design Folder
    */
    export type PartialDesignFolderJson = SampleFoundationPresentation.Folders.PartialDesignFolderJson &  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/BlogModule/Partial Designs
    */
    export type PartialDesigns = SampleFoundationPresentation.PartialDesigns &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/BlogModule/Partial Designs
    */
    export type PartialDesignsJson = SampleFoundationPresentation.PartialDesignsJson &  {
        

    }
}


