
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-jss/sitecore-jss-nextjs';
// @ts-ignore 
import { Sample as SampleProjectSample } from "./Sample.Project.model"
// @ts-ignore 
import { RenderingParams as SampleProjectRenderingParams } from "./Sample.Project.model"
// @ts-ignore 
import { Components as SampleProjectComponents } from "./Sample.Project.model"

export namespace Sample.Project.BlogModule {

    /**
    * Represents the template /sitecore/templates/Project/BlogModule/Blog Detail Page
    */
    export type BlogDetailPage =  {
        fields?: { 
            /**
            * Represents the blogTitle field (f1b4a6c6-2904-4c3c-8d36-f89544b4bd83).
            */
            blogTitle?: Field<string>;

            /**
            * Represents the cardImage field (d62f8ba5-23fc-499c-a8ee-df84ac388c81).
            */
            cardImage?: ImageField;

            /**
            * Represents the Content field (454a5b81-822c-4a51-b70f-5f05d260268f).
            */
            Content?: Field<string>;

            /**
            * Represents the isArchived field (4c6724cc-2202-41dd-9f92-916c9ea477c9).
            */
            isArchived?: Field<boolean>;

            /**
            * Represents the isFeatured field (4c3bc98d-43af-4903-b7a6-1b19defa797b).
            */
            isFeatured?: Field<boolean>;

            /**
            * Represents the publishDate field (ed5a97b9-e726-4c9e-8ff0-d5c6a174acc0).
            */
            publishDate?: Field<string>;

            /**
            * Represents the shortDescription field (504098a7-563e-4e43-b22d-a98849bdab4a).
            */
            shortDescription?: Field<string>;

            /**
            * Represents the Title field (24b7fc00-4509-474a-aa89-fe68ccade2a1).
            */
            Title?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/BlogModule/Blog Detail Page
    */
    export type BlogDetailPageJson =  {
        
            /**
            * Represents the blogTitle field (f1b4a6c6-2904-4c3c-8d36-f89544b4bd83).
            */
            blogTitle?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the cardImage field (d62f8ba5-23fc-499c-a8ee-df84ac388c81).
            */
            cardImage?: {
                jsonValue: ImageField
            };

            /**
            * Represents the Content field (454a5b81-822c-4a51-b70f-5f05d260268f).
            */
            Content?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the isArchived field (4c6724cc-2202-41dd-9f92-916c9ea477c9).
            */
            isArchived?: {
                jsonValue: Field<boolean>
            };

            /**
            * Represents the isFeatured field (4c3bc98d-43af-4903-b7a6-1b19defa797b).
            */
            isFeatured?: {
                jsonValue: Field<boolean>
            };

            /**
            * Represents the publishDate field (ed5a97b9-e726-4c9e-8ff0-d5c6a174acc0).
            */
            publishDate?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the shortDescription field (504098a7-563e-4e43-b22d-a98849bdab4a).
            */
            shortDescription?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Title field (24b7fc00-4509-474a-aa89-fe68ccade2a1).
            */
            Title?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Project/BlogModule/Blogs Page
    */
    export type BlogsPage =  {
        fields?: { 
            /**
            * Represents the Content field (b78ed2bb-bcb1-467c-b847-c3aa16633687).
            */
            Content?: Field<string>;

            /**
            * Represents the Title field (a734ed77-5d16-4461-a063-2916e4045c21).
            */
            Title?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/BlogModule/Blogs Page
    */
    export type BlogsPageJson =  {
        
            /**
            * Represents the Content field (b78ed2bb-bcb1-467c-b847-c3aa16633687).
            */
            Content?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Title field (a734ed77-5d16-4461-a063-2916e4045c21).
            */
            Title?: {
                jsonValue: Field<string>
            };


    }
}
export namespace RenderingParams {

    /**
    * Represents the template /sitecore/templates/Project/BlogModule/Rendering Params/Color
    */
    export type Color =  {
        fields?: { 
            /**
            * Represents the color field (a904edf3-1b3c-4935-98fc-56c7301347ca).
            */
            color?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/BlogModule/Rendering Params/Color
    */
    export type ColorJson =  {
        
            /**
            * Represents the color field (a904edf3-1b3c-4935-98fc-56c7301347ca).
            */
            color?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Project/BlogModule/Rendering Params/ColorParams
    */
    export type ColorParams =  {
        fields?: { 
            /**
            * Represents the backgroundColor field (58e154ea-c655-415a-b149-cf2ae0bc10dd).
            */
            backgroundColor?: Field<string>;

            /**
            * Represents the textColor field (8d0c5b20-8e99-4fb3-a365-ffa72c2ae619).
            */
            textColor?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/BlogModule/Rendering Params/ColorParams
    */
    export type ColorParamsJson =  {
        
            /**
            * Represents the backgroundColor field (58e154ea-c655-415a-b149-cf2ae0bc10dd).
            */
            backgroundColor?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the textColor field (8d0c5b20-8e99-4fb3-a365-ffa72c2ae619).
            */
            textColor?: {
                jsonValue: Field<string>
            };


    }
}
export namespace Sample.Project.BlogModule {

    /**
    * Represents the template /sitecore/templates/Project/BlogModule/Folder
    */
    export type Folder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/BlogModule/Folder
    */
    export type FolderJson =  {
        

    }
}
export namespace Components.Header {

    /**
    * Represents the template /sitecore/templates/Project/BlogModule/Components/Header/Header
    */
    export type Header =  {
        fields?: { 
            /**
            * Represents the Logo field (abc2325b-9e41-48f9-af64-534f54c698f6).
            */
            Logo?: ImageField;

            /**
            * Represents the Navigation field (144ce21d-0eeb-4dc0-8a99-059cf37a1ea7).
            */
            Navigation?: Item;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/BlogModule/Components/Header/Header
    */
    export type HeaderJson =  {
        
            /**
            * Represents the Logo field (abc2325b-9e41-48f9-af64-534f54c698f6).
            */
            Logo?: {
                jsonValue: ImageField
            };

            /**
            * Represents the Navigation field (144ce21d-0eeb-4dc0-8a99-059cf37a1ea7).
            */
            Navigation?: {
                jsonValue: Item
            };


    }

    /**
    * Represents the template /sitecore/templates/Project/BlogModule/Components/Header/HeaderFolder
    */
    export type HeaderFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/BlogModule/Components/Header/HeaderFolder
    */
    export type HeaderFolderJson =  {
        

    }
}
export namespace Sample.Project.BlogModule {

    /**
    * Represents the template /sitecore/templates/Project/BlogModule/Headless Site
    */
    export type HeadlessSite =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/BlogModule/Headless Site
    */
    export type HeadlessSiteJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/BlogModule/Headless Tenant
    */
    export type HeadlessTenant =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/BlogModule/Headless Tenant
    */
    export type HeadlessTenantJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/BlogModule/JSS Settings
    */
    export type JssSettings =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/BlogModule/JSS Settings
    */
    export type JssSettingsJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/BlogModule/Local Datasource
    */
    export type LocalDatasource =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/BlogModule/Local Datasource
    */
    export type LocalDatasourceJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/BlogModule/Page
    */
    export type Page =  {
        fields?: { 
            /**
            * Represents the Content field (eeb762f5-de26-4167-9d61-332e6f3ad736).
            */
            Content?: Field<string>;

            /**
            * Represents the Title field (3575001e-8722-4307-b42f-ec27194089aa).
            */
            Title?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/BlogModule/Page
    */
    export type PageJson =  {
        
            /**
            * Represents the Content field (eeb762f5-de26-4167-9d61-332e6f3ad736).
            */
            Content?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Title field (3575001e-8722-4307-b42f-ec27194089aa).
            */
            Title?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Project/BlogModule/Page Design Folder
    */
    export type PageDesignFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/BlogModule/Page Design Folder
    */
    export type PageDesignFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/BlogModule/Page Designs
    */
    export type PageDesigns =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/BlogModule/Page Designs
    */
    export type PageDesignsJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/BlogModule/Partial Design Folder
    */
    export type PartialDesignFolder =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/BlogModule/Partial Design Folder
    */
    export type PartialDesignFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/BlogModule/Partial Designs
    */
    export type PartialDesigns =  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/BlogModule/Partial Designs
    */
    export type PartialDesignsJson =  {
        

    }
}


