
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-jss/sitecore-jss-nextjs';
// @ts-ignore 
import { Sample as SampleProjectSample } from "./Sample.Project.model"
// @ts-ignore 
import { Multisite as SampleFoundationMultisite } from "./Sample.Foundation.model"
// @ts-ignore 
import { Presentation as SampleFoundationPresentation } from "./Sample.Foundation.model"

export namespace Sample.Project.BlogModule {

    /**
    * Represents the template /sitecore/templates/Project/BlogModule/Headless Site
    */
    export type HeadlessSite = SampleFoundationMultisite.HeadlessSite &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/BlogModule/Headless Site
    */
    export type HeadlessSiteJson = SampleFoundationMultisite.HeadlessSiteJson &  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/BlogModule/Headless Tenant
    */
    export type HeadlessTenant = SampleFoundationMultisite.HeadlessTenant &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/BlogModule/Headless Tenant
    */
    export type HeadlessTenantJson = SampleFoundationMultisite.HeadlessTenantJson &  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/BlogModule/JSS Settings
    */
    export type JssSettings = SampleFoundationMultisite.JssSettings &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/BlogModule/JSS Settings
    */
    export type JssSettingsJson = SampleFoundationMultisite.JssSettingsJson &  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/BlogModule/Page
    */
    export type Page = SampleFoundationMultisite.BasePage &  {
        fields?: { 
            /**
            * Represents the Content field (eeb762f5-de26-4167-9d61-332e6f3ad736).
            */
            Content?: Field<string>;

            /**
            * Represents the Title field (3575001e-8722-4307-b42f-ec27194089aa).
            */
            Title?: Field<string>;
        }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/BlogModule/Page
    */
    export type PageJson = SampleFoundationMultisite.BasePageJson &  {
        
            /**
            * Represents the Content field (eeb762f5-de26-4167-9d61-332e6f3ad736).
            */
            Content?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Title field (3575001e-8722-4307-b42f-ec27194089aa).
            */
            Title?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Project/BlogModule/Page Design Folder
    */
    export type PageDesignFolder = SampleFoundationPresentation.Folders.PageDesignFolder &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/BlogModule/Page Design Folder
    */
    export type PageDesignFolderJson = SampleFoundationPresentation.Folders.PageDesignFolderJson &  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/BlogModule/Page Designs
    */
    export type PageDesigns = SampleFoundationPresentation.PageDesigns &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/BlogModule/Page Designs
    */
    export type PageDesignsJson = SampleFoundationPresentation.PageDesignsJson &  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/BlogModule/Partial Design Folder
    */
    export type PartialDesignFolder = SampleFoundationPresentation.Folders.PartialDesignFolder &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/BlogModule/Partial Design Folder
    */
    export type PartialDesignFolderJson = SampleFoundationPresentation.Folders.PartialDesignFolderJson &  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/BlogModule/Partial Designs
    */
    export type PartialDesigns = SampleFoundationPresentation.PartialDesigns &  {
        fields?: {         }

    }

    /**
    * Represents the GraphQL template /sitecore/templates/Project/BlogModule/Partial Designs
    */
    export type PartialDesignsJson = SampleFoundationPresentation.PartialDesignsJson &  {
        

    }
}


